# Generated by Django 4.0.3 on 2022-04-12 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catube', '0003_tag_alter_comment_id_alter_video_id_video_tag_set'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='video',
            name='liked_user_set',
            field=models.ManyToManyField(blank=True, related_name='liked_video_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
